src/salesforce/retrieve/metadata/objects/CustomSettingObject__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>RemoteSiteURLField__c</fullName>
        <label>RemoteSiteURLField</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CustomSettingObject</label>
</CustomObject>

src/salesforce/retrieve/metadata/classes/CalloutClassTest.cls
@isTest
public class CalloutClassTest 
{
    static 
    {
        CustomSettingObject__c customSettingObject = new CustomSettingObject__c();
        customSettingObject.Name = 'RemoteSiteURL';
        customSettingObject.RemoteSiteURLField__c = 'http://23.251.129.95:8080/';
        insert customSettingObject;
    }
    
	@isTest 
    static void testCallout() 
     {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        Integer res = EntityListController.generateEntities();
         
        System.assertEquals(200, res);
    }
}