src/salesforce/retrieve/metadata/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>EntityId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>EntityId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/objects/NotificationMessage__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>ExternalId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OperationType__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>OperationType</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SObjectType__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>SObjectType</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NotificationMessage</label>
    <nameField>
        <label>NotificationMessage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NotificationMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/classes/EntityObjectDomain.cls
public with sharing class EntityObjectDomain extends SObjectDomain
{
    public EntityObjectDomain(List<SObject> records)
    {
        super(records);
    }

    public class Constructor implements SObjectDomain.Constructable
    {
        public SObjectDomain construct(List<SObject> records)
        {
            return new EntityObjectDomain(records);
        }
    }

    public override void onAfterInsert()
    {
       insertMessage(OperationType.INSERT_OPERATION);
    }

    public override void onAfterUpdate(Map<Id, SObject> existingRecords)
    {
        insertMessage(OperationType.INSERT_OPERATION);
    }

    public override void onAfterDelete()
    {
        insertMessage(OperationType.DELETE_OPERATION);
    }

    private void insertMessage(OperationType operationType)
    {
        for (Entity__c entity : (List<Entity__c>) records)
        {
            NotificationMessage__c message = new NotificationMessage__c();

            message.OperationType__c = String.valueOf(operationType);
            message.SObjectType__c = 'Entity';
            message.ExternalId__c = entity.EntityId__c;

            Database.insert(message);
        }
    }
}