src/salesforce/retrieve/metadata/objects/Entity__c.object
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>ColumnName__c</fullName>
        <label>ColumnName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FieldId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>FieldId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/classes/FieldUtil.cls
public class FieldUtil 
{
	public static void generateColumnNameAndExternalId(List<Field__c>fields)
    {
		Set<Id> entityIds = new Set<Id>();
		for (Field__c field : fields)
		{
			entityIds.add(field.Entity__c);
		} 
        
		Map<Id, Entity__c> entityByName = new Map<Id, Entity__c>(
		[
			SELECT Id, Name 
			FROM Entity__c
			WHERE Id IN :entityIds
		]);
        
		for (Field__c field : fields)
		{
			Entity__c entity = entityByName.get(field.Entity__c);
			field.ColumnName__c = field.Name.replaceAll('\\s','_')
			.replaceAll('\\W','')
			.replaceAll('\\d', '')
			.toUpperCase();
            
			field.FieldId__c = entity.Name.replaceAll('\\s','')
			.replaceAll('\\W','')
			.replaceAll('\\d', '')+'.';
			field.FieldId__c += field.Name.replaceAll('\\s','')
			.replaceAll('\\W','')
			.replaceAll('\\d', '');       
		}
	}
}