src/salesforce/retrieve/metadata/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>EntityId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>EntityId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TableName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>TableName</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/classes/EntityUtil.cls
import com.sforce.soap.enterprise.sobject.Entity__c;

import java.util.List;

public class EntityUtil
{
    public static void generateEntityTable(List<Entity__c> entities)
    {
       for(Entity__c entity : entities)
   		{
   		    String tableName = entity.TableName__c
                                                    .replaceAll('\\s','')
                                                    .replaceAll('\\W','')
                                                    .replaceAll('_','')
                                                    .replaceAll('\\d', '');

            entity.TableName__c = entity.TableName__c
                                                    .replaceAll('\\s','_')
                                                    .replaceAll('\\W','')
                                                    .replaceAll('\\d', '')
                                                    .toUpperCase();

            entity.EntityId__c = tableName.toLowerCase();
    	}
    }

    public static void resetIsProcessingNeeded()
    {
        for (Entity__c :
        [
            SELECT
        ])
    }
}