src/salesforce/retrieve/metadata/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>TableName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>TableName</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/classes/InsertTableNameTest.cls
@isTest
public class InsertTableNameTest 
{ 
    static testMethod void testTableNameTrigger()
    {
        Entity__c entity = new Entity__c();
        entity.TableName__c = 'entityTestTableName';
        entity.Name = 'testName';
        
        test.startTest();
        
        Database.SaveResult result = Database.insert(entity);
        
        test.stopTest();
        
        System.assert(result.isSuccess());          
    }
}