src/salesforce/retrieve/metadata/objects/Entity__c.object
<CustomObject>
    <fields>
        <fullName>TableName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>TableName</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/objects/Field__c.object
<CustomObject>
    <fields>
        <fullName>ColumnName__c</fullName>
        <label>ColumnName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Entity__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsPrimaryKey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPrimaryKey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>date</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>int</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>varchar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/classes/InsertColumnNameTest.cls
@isTest
public class InsertColumnNameTest 
{
 static testMethod void testColumnNameTrigger()
    {      
        test.startTest();
       
        Entity__c entityTest = new Entity__c();
        entityTest.TableName__c = 'entityTableNameTest';
        entityTest.Name = 'entityNameTest';
        
        Database.insert(entityTest);
        
        Field__c fieldTest = new Field__c();
        fieldTest.ColumnName__c = 'fieldColumnName';
        fieldTest.Name = 'fieldTest';
        fieldTest.Type__c = 'int';
        fieldTest.IsPrimaryKey__c = false;
        fieldTest.Entity__c = entityTest.Id;
        
        Database.SaveResult result = Database.insert(fieldTest);  
        
        test.stopTest();
        
        System.assert(result.isSuccess());          
    }
}