src/salesforce/retrieve/metadata/objects/NotificationMessage__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>ExternalId</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OperationType__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>OperationType</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SObjectType__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>SObjectType</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NotificationMessage</label>
    <nameField>
        <label>NotificationMessage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NotificationMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/salesforce/retrieve/metadata/classes/NotificationMessageUtil.cls
public class NotificationMessageUtil
{
    public static void insertMessage(List<SObject> sObjects, OperationType operationType, String masterRelationName)
    {
        for (SObject sObjectToProcess : sObjects)
        {
            NotificationMessage__c message = new NotificationMessage__c();

            String sObjectType = String.valueOf(sObjectToProcess.getSObjectType());

            message.SObjectType__c = sObjectType;
            message.OperationType__c = String.valueOf(operationType);

            if (masterRelationName == null)
            {
                message.ExternalId__c = String.valueOf(sObjectToProcess.get(toExternalIdFieldName(sObjectType)));
            }
            else
            {
                SObject masterRelation = sObjectToProcess.getSObject(masterRelationName);
                message.ExternalId__c = String.valueOf(
                        masterRelation.get(
                                toExternalIdFieldName(String.valueOf(masterRelation.getSObjectType()))
                        )
                );
            }
            Database.insert(message);
        }
    }

    private static String toExternalIdFieldName(String sObjectType)
    {
        return sObjectType.replace('__c', 'Id__c');
    }
}